### ISSUE TITLE
Hardcore mode issue

### ISSUE THREAD

**Issue by amzaldua** [williamcorsel/hassio-addons#12]
Hi!

I can't to set de hardcore mode. I choose the option in the configuration tab and then when I restart the server the hardcore mode is not working.

**Comment by aph-le** [comment]
Hi, as I wrote in a other discussion:

_I had the same problems with the configuration in the bedrock version. But since this add-on is based on iztg image it's hard to change. So I created a new add-on (Spawn-Point-Bedrock) to address this issues directly. It's inspired by this and iztg (many thanks).
Comments and contributions are welcome._
